### ISSUE TITLE
Type board password to upload a new sketch

### ISSUE THREAD

**Issue by gspitman** [me-no-dev/RasPiArduino#104]
Getting the above prompt from Arduino ide,

I enter my root "pi user" password but the prompt returns. Any ideas?

**Comment by doitandbedone** [comment]
I am also having trouble when authenticating, the root password works when connecting directly to SSH however.
Here are the logs:
processing.app.debug.RunnerException
	at cc.arduino.packages.uploaders.SSHUploader.uploadUsingPreferences(SSHUploader.java:150)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2055)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@24590fc4
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:620)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:542)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:389)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:349)
	at com.jcraft.jsch.Session.applyConfig(Session.java:2665)
	at com.jcraft.jsch.Session.<init>(Session.java:166)
	at com.jcraft.jsch.JSch.getSession(JSch.java:256)
	at com.jcraft.jsch.JSch.getSession(JSch.java:208)
	at cc.arduino.packages.ssh.SSHConfigFileSetup.setup(SSHConfigFileSetup.java:64)
	at cc.arduino.packages.uploaders.SSHUploader.uploadUsingPreferences(SSHUploader.java:117)
	... 5 more

Running macOS 10.15.6
