### ISSUE TITLE
#include <Bridge.h> causes compiling error after first time uploading

### ISSUE THREAD

**Issue by CollinKasbergen** [me-no-dev/RasPiArduino#79]
Somehow when I try to use <Bridge.h> its works fine when compelling the first time but when I want to compile and upload it another time I have to restart the IDE otherwise I get this error: 

`panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x1559e0, 0xc4200140b0)
	/home/jenkins/go/src/runtime/panic.go:500 +0x1a1
arduino.cc/builder.findIncludesUntilDone(0xc420058400, 0xc420010180, 0x155d00, 0xc4200bf1d0, 0xc42025fcd2, 0xa, 0x0, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/container_find_includes.go:321 +0x138f
arduino.cc/builder.(*ContainerFindIncludes).Run(0x24ac18, 0xc420058400, 0x41bc3c3c, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/container_find_includes.go:149 +0x5e4
arduino.cc/builder.runCommands(0xc420058400, 0xc42046dae8, 0x22, 0x22, 0x1, 0x0, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:191 +0xcd
arduino.cc/builder.(*Builder).Run(0xc42046dd38, 0xc420058400, 0xc42003fd88, 0x160d80)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:124 +0xb9c
arduino.cc/builder.RunBuilder(0xc420058400, 0xc42003fd88, 0x24ac18)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:222 +0x35
main.main()
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/arduino-builder/main.go:338 +0x99c
/Applications/Arduino.app/Contents/Java/arduino-builder returned 2
Error compiling for board RaspberryPI B+/2.`

**Comment by microbrewer** [comment]
This looks like a well-known bug in the IDE under Linux, introduced in 1.6.12: http://www.chipkit.net/forum/viewtopic.php?f=7&t=3753
Do you have the same issue with other libraries as well? If so, try downgrading to 1.6.11 and see if the problem persists.
